stages:
  - build-push-image

build-push-image:
  image: docker:latest
  stage: build-push-image
  only:
    - main
  services:
    - docker:dind

  variables:
    GIT_SUBMODULE_STRATEGY: 'recursive'
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay
    CONTAINER_RELEASE_IMAGE: registry.gitlab.com/oatfin/demo-ui:latest

  before_script:
    - docker info
    - docker login -u gitlab+deploy-token-1875812 -p wn7h-9RJsyPSXFrQGhED registry.gitlab.com
    - docker volume prune -f

  script:
    - rm -rf /tmp
    - docker build --cache-from $CONTAINER_RELEASE_IMAGE -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE
